### ISSUE TITLE
Add Frontend Design for PWA

### ISSUE THREAD

**Issue by adithya-s-k** [adithya-s-k/Phoenix#1]
---
Title: Phoenix
About:  Add Frontend Design for PWA
Name: [adithya-s-k](https://github.com/adithya-s-k)
Label: Feature Request

---

**Is your feature request related to a problem? Please describe.**
Add a frontend to the Progressive Web App to connect with the UAV

**Describe the solution you'd like...**
Basic React based Frontend to get started with

**Additional notes**

N/A

**Comment by Sakthe-Balan** [comment]
I would like to work on this issue

**Comment by adithya-s-k** [comment]
Approved!
