### ISSUE TITLE
Changes in Footer, Navbar, and Image Path Updates in the ECommerce Directory

### ISSUE THREAD

**Issue by adithya-s-k** [adithya-s-k/Phoenix#11]
---
Title: Phoenix
About:  Changes in Footer, Navbar, and Image Path Updates
Name: [adithya-s-k](https://github.com/adithya-s-k)
Label: Feature Request

---

*Is your feature request related to a problem? Please describe.*
 Changes in Footer, Navbar, and Image Path Updates in the ECommerce Directory

*Additional notes*

N/A

**Comment by SarthakSKumar** [comment]
Can I work on this issue?
