### ISSUE TITLE
Update README.md for the Project Directory

### ISSUE THREAD

**Issue by adithya-s-k** [adithya-s-k/Phoenix#12]
---
Title: Phoenix
About: Update README.md for the Project Repository
Name: [adithya-s-k](https://github.com/adithya-s-k)
Label: Feature Request

---

*Is your feature request related to a problem? Please describe.*
Update README.md for the Project Repository

*Additional notes*

N/A

**Comment by SarthakSKumar** [comment]
I will work on this issue
