### ISSUE TITLE
Work on deployment of Phoenix Website

### ISSUE THREAD

**Issue by adithya-s-k** [adithya-s-k/Phoenix#13]
---
Title: Phoenix
About:  Work on deployment of Phoenix Website
Name: [adithya-s-k](https://github.com/adithya-s-k)
Label: Feature Request

---

*Is your feature request related to a problem? Please describe.*
Work on deployment of Phoenix Website. Go Ahead with GH Pages. Deploy in the upstream repository

*Additional notes*

N/A

**Comment by SarthakSKumar** [comment]
I will work on this issue
