### ISSUE TITLE
Add Project Related Content in Frontend Website

### ISSUE THREAD

**Issue by adithya-s-k** [adithya-s-k/Phoenix#3]
---
Title: Phoenix
About:  Add Project Related Content in Frontend Website
Name: [adithya-s-k](https://github.com/adithya-s-k)
Label: Feature Request

---

*Is your feature request related to a problem? Please describe.*
Add a frontend with project content to the Progressive Web App to connect with the UAV

*Describe the solution you'd like...*
Basic Vanilla Frontend to get started with, including the project content

*Additional notes*

N/A

**Comment by Sakthe-Balan** [comment]
Can i work on this
