### ISSUE TITLE
Add E-Commerce Website Design, Relavant Files, Update in Repository

### ISSUE THREAD

**Issue by adithya-s-k** [adithya-s-k/Phoenix#9]
---
Title: Phoenix
About:  Add E-Commerce Website Design, Relavant Files, Update in Repository
Name: [SarthakSKumar](https://github.com/SarthakSKumar)
Label: Feature Request

---

*Is your feature request related to a problem? Please describe.*
Add E-Commerce Website Design, Relavant Files, Update in Repository

*Additional notes*

N/A

**Comment by SarthakSKumar** [comment]
Please assign @adithya-s-k
